kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
  - name: Restore Cache
    commands:
      - |
        docker run --rm \
          -v "$(pwd)":/app \
          -v /tmp/drone:/tmp/cache \
          -e PLUGIN_BACKEND=filesystem \
          -e PLUGIN_MOUNT="app/tools/.bin,app/tools/.mint" \
          -e PLUGIN_CACHE_KEY="$(md5 -q tools/mint)-$(md5 -q Mintfile)" \
          -e PLUGIN_RESTORE=true \
          meltwater/drone-cache

  - name: Run CI script
    commands:
    - scripts/run_ci.sh

  - name: Rebuild Cache
    commands:
      - |
        docker run --rm \
          -v "$(pwd)":/app \
          -v /tmp/drone:/tmp/cache \
          -e PLUGIN_BACKEND=filesystem \
          -e PLUGIN_MOUNT="app/tools/.bin,app/tools/.mint" \
          -e PLUGIN_CACHE_KEY="$(md5 -q tools/mint)-$(md5 -q Mintfile)" \
          -e PLUGIN_REBUILD=true \
          -e PLUGIN_DEBUG=true \
          meltwater/drone-cache
