name: Magnesium
options:
  minimumXcodeGenVersion: 2.42.0
configFiles:
  Debug: config/Debug.xcconfig
  Release: config/Release.xcconfig
packages:
  Deluge:
    # path: ../Deluge-Swift
    url: https://github.com/NinjaLikesCheez/Deluge-Swift
    from: 1.2.0
  QBittorrent:
    path: ../QBittorrent-Swift
    # url: https://github.com/NinjaLikesCheez/QBittorrent-Swift
    # branch: main
  ObservableDefaults:
    # path: ../../fatbobman/ObservableDefaults
    url: https://github.com/NinjaLikesCheez/ObservableDefaults
    branch: allow-optionals
  Logging:
    url: https://github.com/apple/swift-log
    from: 1.6.2
  Router:
    url: https://github.com/NinjaLikesCheez/Router
    from: 1.0.0
targets:
  Magnesium:
    type: application
    supportedDestinations: [iOS, tvOS, macOS, visionOS]
    deploymentTarget:
      iOS: 18.4
      tvOS: 18.4
      macOS: 15.4
      visionOS: 2.0
    sources:
      - Sources/Magnesium
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: bykim.cracks.Magnesium
    info:
      path: Sources/Magnesium/Resources/Info.plist
      properties:
        CFBundleDisplayName: Magnesium
        CFBundleIdentifier: bykim.cracks.Magnesium
        UILaunchScreen:
          UIColorName: White
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    configFiles:
      Debug: config/Magnesium-Debug.xcconfig
      Release: config/Magnesium-Release.xcconfig
    dependencies:
      - package: Deluge
      - package: QBittorrent
      - package: Logging
      - package: ObservableDefaults
      - package: Router
    scheme:
      testTargets:
        - MagnesiumTests
      gatherCoverageData: true
      coverageTargets:
        - Magnesium
  MagnesiumTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, tvOS, macOS, visionOS]
    sources:
      - Tests
    dependencies:
      - target: Magnesium
    settings:
      GENERATE_INFOPLIST_FILE: YES
