skip_docs
default_platform(:ios)

DERIVED_DATA_PATH = "fastlane/build"
TEST_DEVICE = "iPhone 8"

platform :ios do
  desc "Runs actions for CI"
  lane :run_ci do
    test_preferences
    test_magnesium
    build
  end

  desc "Runs all tests"
  lane :test do
    test_preferences
    test_magnesium
  end

  desc "Runs Preferences tests"
  lane :test_preferences do
    run_tests(
      scheme: "Preferences",
      clean: true,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      prelaunch_simulator: true,
      device: TEST_DEVICE
    )
    slather(
      proj: "Magnesium.xcodeproj",
      scheme: "Preferences",
      build_directory: DERIVED_DATA_PATH,
      html: true,
      output_directory: "fastlane/coverage_report/Preferences"
    )
  end

  desc "Runs Magnesium tests"
  lane :test_magnesium do
    run_tests(
      scheme: "Magnesium",
      clean: true,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      prelaunch_simulator: true,
      device: TEST_DEVICE
    )
    slather(
      proj: "Magnesium.xcodeproj",
      scheme: "Magnesium",
      build_directory: DERIVED_DATA_PATH,
      html: true,
      output_directory: "fastlane/coverage_report/Magnesium",
      ignore: ["MVVM/*", "Preferences/*", "Deluge/*", "Transmission/*", "**/Preview*.swift"]
    )
  end

  desc "Creates a release build"
  lane :build do
    build_app(
      scheme: "Magnesium",
      configuration: "Release",
      clean: true,
      derived_data_path: DERIVED_DATA_PATH,
      output_directory: "fastlane/build_output",
      export_method: "development"
    )
  end
end
