skip_docs
default_platform(:ios)

DERIVED_DATA_PATH = "fastlane/build"
TEST_DEVICE = "iPhone 8"

xcversion(version: ">= 11.4")

platform :ios do
  desc "Runs actions for CI"
  lane :run_ci do
    test
    build
  end

  desc "Runs all tests"
  lane :test do
    test_magnesium
  end

  desc "Runs Magnesium tests"
  lane :test_magnesium do
    run_tests(
      scheme: "Magnesium",
      clean: true,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      prelaunch_simulator: true,
      device: TEST_DEVICE
    )
    slather(
      proj: "Magnesium.xcodeproj",
      scheme: "Magnesium",
      build_directory: DERIVED_DATA_PATH,
      html: true,
      output_directory: "fastlane/coverage_report",
      ignore: [
        "fastlane/*",
        "Libraries/*",
        "**/Models/*",
        "**/*ViewController.swift",
        "**/*View.swift",
        "**/*ViewCell.swift",
        "**/*Button.swift",
        "Magnesium/App/AppDelegate.swift",
        "Magnesium/App/SceneDelegate.swift",
        "Magnesium/Common/Activity/*.swift",
        "Magnesium/Common/Extensions/UIImage+Color.swift",
        "Magnesium/Common/Extensions/Publishers+UI.swift",
        ]
    )
  end

  desc "Creates a release build"
  lane :build do
    build_app(
      scheme: "Magnesium",
      configuration: "Release",
      clean: true,
      derived_data_path: DERIVED_DATA_PATH,
      output_directory: "fastlane/build_output",
      export_method: "development"
    )
  end
end
