skip_docs
default_platform(:ios)

DERIVED_DATA_PATH = "fastlane/build"
TEST_DEVICE = "iPhone 11 Pro"

xcversion(version: ">= 11.4")

platform :ios do
  desc "Runs actions for CI"
  lane :run_ci do
    test
    build
  end

  desc "Runs all tests"
  lane :test do
    test_magnesium(coverage: true)
  end

  desc "Runs Magnesium tests"
  lane :test_magnesium do |options|
    run_tests(
      scheme: "Magnesium",
      clean: true,
      code_coverage: true,
      derived_data_path: DERIVED_DATA_PATH,
      prelaunch_simulator: true,
      device: TEST_DEVICE
    )

    if options[:coverage]
      slather(
        proj: "Magnesium.xcodeproj",
        scheme: "Magnesium",
        build_directory: DERIVED_DATA_PATH,
        html: true,
        show: options[:show_coverage],
        output_directory: "fastlane/coverage_report",
        ignore: [
          "fastlane/*",
          "Components/*",
          "Magnesium/App/AppDelegate.swift",
          "Magnesium/App/SceneDelegate.swift"
          ]
      )
    end
  end

  desc "Creates a release build"
  lane :build do
    build_app(
      scheme: "Magnesium",
      configuration: "Release",
      clean: true,
      derived_data_path: DERIVED_DATA_PATH,
      output_directory: "fastlane/build_output",
      export_method: "development"
    )
  end

  desc "Regenerates snapshots"
  lane :regenerate_snapshots do
    sh "cd ../ && find MagnesiumTests -type d -name __Snapshots__  | xargs rm -rf"
    test_magnesium
  end
end
